name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Flake8 check
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Package creation
        run: |
          sudo apt install python3-setuptools python3-stdeb dh-python python3-all fakeroot
          pip install pipreqs stem stdeb wheel
          pip install setuptools wheel
          python3 setup.py sdist
          python3 setup.py bdist_wheel

#          python3 -m  pipreqs.pipreqs .

#Setting->Actions->General->Workflow permissions->"Read and write permissions"
      - name: Git push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -f ./dist/*.whl
          git commit -m 'pushing new wheel'
          git push
